// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxLAaKqsneUHs-jqCbHbsUj0Ki_LSyrVs',
    appId: '1:902146083742:web:0f25139f7abe849fdce48f',
    messagingSenderId: '902146083742',
    projectId: 'aihanif-dart',
    authDomain: 'aihanif-dart.firebaseapp.com',
    storageBucket: 'aihanif-dart.firebasestorage.app',
    measurementId: 'G-QDF40MPKSQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhsDRPI_utCzrLbCfQEQbFaegkcGuigdQ',
    appId: '1:902146083742:android:3dd29d7828dceb1adce48f',
    messagingSenderId: '902146083742',
    projectId: 'aihanif-dart',
    storageBucket: 'aihanif-dart.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYsv2Q7fCHFYxm0Bv6_eicEciD0_DBDKw',
    appId: '1:902146083742:ios:f8e47ecdd2a45406dce48f',
    messagingSenderId: '902146083742',
    projectId: 'aihanif-dart',
    storageBucket: 'aihanif-dart.firebasestorage.app',
    iosBundleId: 'com.uthm.flexipos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYsv2Q7fCHFYxm0Bv6_eicEciD0_DBDKw',
    appId: '1:902146083742:ios:f8e47ecdd2a45406dce48f',
    messagingSenderId: '902146083742',
    projectId: 'aihanif-dart',
    storageBucket: 'aihanif-dart.firebasestorage.app',
    iosBundleId: 'com.uthm.flexipos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDY9huTcv5d4oCBfw_kxzzcsXcD69sUFek',
    appId: '1:902146083742:web:9e9c246517576473dce48f',
    messagingSenderId: '902146083742',
    projectId: 'aihanif-dart',
    authDomain: 'aihanif-dart.firebaseapp.com',
    storageBucket: 'aihanif-dart.firebasestorage.app',
    measurementId: 'G-93LZD9FFXZ',
  );
}
